apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '14.3.3'
    chart: postgresql
    helm:
      parameters:
        - name: global.postgresql.auth.postgresPassword
          value: "admin"
        - name: volumePermissions.enabled
          value: "true"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

