apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress
  namespace: argo
spec:
  project: default
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: "26.1.0"
    chart: traefik
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
